name: Ejecutar Script

on:
  schedule:
    - cron: "* * * * *"

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ejecutar mantenerActivo.py
        run: python mantenerActivo.py
